"""create today detail table

Revision ID: 2044f795f260
Revises: 4c6d3ad495c0
Create Date: 2014-03-05 16:01:20.901980

"""

# revision identifiers, used by Alembic.
revision = '2044f795f260'
down_revision = '4c6d3ad495c0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('today_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('today_date', sa.Date(), nullable=True),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('result_name', sa.String(length=120), nullable=True),
    sa.Column('result_thumbnail', sa.String(length=180), nullable=True),
    sa.Column('result_thumbnail_width', sa.SmallInteger(), nullable=True),
    sa.Column('result_thumbnail_height', sa.SmallInteger(), nullable=True),
    sa.Column('result_image', sa.String(length=180), nullable=True),
    sa.Column('result_width', sa.SmallInteger(), nullable=True),
    sa.Column('result_height', sa.SmallInteger(), nullable=True),
    sa.Column('result_created_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=80), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_today_detail_result_id', 'today_detail', ['result_id'], unique=True)
    op.create_index('ix_today_detail_today_date', 'today_detail', ['today_date'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_today_detail_today_date', table_name='today_detail')
    op.drop_index('ix_today_detail_result_id', table_name='today_detail')
    op.drop_table('today_detail')
    ### end Alembic commands ###
