"""create user_connection table

Revision ID: 277bff62adde
Revises: 5138046dc214
Create Date: 2014-02-18 21:09:28.827701

"""

# revision identifiers, used by Alembic.
revision = '277bff62adde'
down_revision = '5138046dc214'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_connection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_name', sa.String(length=30), nullable=True),
    sa.Column('provider_user_id', sa.String(length=30), nullable=True),
    sa.Column('access_token', sa.String(length=80), nullable=True),
    sa.Column('display_name', sa.String(length=50), nullable=True),
    sa.Column('profile_url', sa.String(length=180), nullable=True),
    sa.Column('avatar_url', sa.String(length=180), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_connection')
    ### end Alembic commands ###
