"""create stream table

Revision ID: 29a5c2ff811f
Revises: db9f85e0389
Create Date: 2014-02-12 17:07:05.604262

"""

# revision identifiers, used by Alembic.
revision = '29a5c2ff811f'
down_revision = 'db9f85e0389'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stream',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('result_id', sa.Integer(), nullable=True),
    sa.Column('result_name', sa.String(length=120), nullable=True),
    sa.Column('result_thumbnail', sa.String(length=180), nullable=True),
    sa.Column('result_thumbnail_width', sa.SmallInteger(), nullable=True),
    sa.Column('result_thumbnail_height', sa.SmallInteger(), nullable=True),
    sa.Column('result_image', sa.String(length=180), nullable=True),
    sa.Column('result_width', sa.SmallInteger(), nullable=True),
    sa.Column('result_height', sa.SmallInteger(), nullable=True),
    sa.Column('result_created_at', sa.DateTime(), nullable=True),
    sa.Column('filename', sa.String(length=80), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_stream_result_id', 'stream', ['result_id'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stream_result_id', table_name='stream')
    op.drop_table('stream')
    ### end Alembic commands ###
