"""create user_settings table

Revision ID: 51a381a6d26c
Revises: 2ea125c04ba1
Create Date: 2014-06-21 00:54:47.334873

"""

# revision identifiers, used by Alembic.
revision = '51a381a6d26c'
down_revision = '2ea125c04ba1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('public_profile', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_settings')
    ### end Alembic commands ###
