"""create bookmark table

Revision ID: 5461b62bfa1d
Revises: 29a5c2ff811f
Create Date: 2014-02-13 15:59:01.642428

"""

# revision identifiers, used by Alembic.
revision = '5461b62bfa1d'
down_revision = '29a5c2ff811f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmark',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('stream', 'the_of_girl'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_bookmark_target_id', 'bookmark', ['target_id'], unique=False)
    op.create_index('ix_bookmark_user_id', 'bookmark', ['user_id'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_bookmark_user_id', table_name='bookmark')
    op.drop_index('ix_bookmark_target_id', table_name='bookmark')
    op.drop_table('bookmark')
    ### end Alembic commands ###
