"""create user table

Revision ID: db9f85e0389
Revises: None
Create Date: 2014-02-12 16:41:15.913121

"""

# revision identifiers, used by Alembic.
revision = 'db9f85e0389'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=True),
    sa.Column('token', sa.String(length=20), nullable=True),
    sa.Column('screen_name', sa.String(length=80), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.Column('update_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_username', 'user', ['username'], unique=True)
    op.create_index('ix_user_email', 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_username', table_name='username')
    op.drop_index('ix_user_email', table_name='user')
    op.drop_table('user')
    ### end Alembic commands ###
